[HIRFUS-9] Printing Product Price with javascript
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1014
Opened 2022-04-14 20:39 UTC by AaronAsborn

i Just completed my first js task and have made a PR

2022-04-16 12:40 UTC, ToluEnny24 requested changes
Please effect the requested changes. @AaronAsborn you have not been adding the screenshots to your pull request.

2022-04-16 12:40 UTC, ToluEnny24 commented on submissions/aaronMubanga/javascript/printingProducts/product_price.html
> +    <style>
Good coding practice is that styles should not been added to the html page.

2022-04-18 16:38 UTC, AaronAsborn commented
![Screenshot 2022-04-18 at 18-24-00 Product_Printing](https://user-images.githubusercontent.com/93948423/163840757-c91b953e-01ee-4960-8a16-bf28d085ff3a.png)

2022-04-18 18:03 UTC, ToluEnny24 approved these changes

2022-04-18 18:04 UTC, merged