[DGPFUS-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1026
Opened 2022-04-16 14:47 UTC by ChijiokeOrabueze

In this PR,

- I wrote sql code for a transportation company database design.

2022-04-18 18:10 UTC, ToluEnny24 requested changes
Well done @ChijiokeOrabueze Please effect the requested changes

2022-04-18 18:10 UTC, ToluEnny24 commented on submissions/chijiokeOrabueze/database2/database2.sql
> +    full_name VARCHAR(100) NOT NULL,
100 characters is too smalll, change to 250

2022-04-18 18:10 UTC, ToluEnny24 commented on submissions/chijiokeOrabueze/database2/database2.sql
> +    passenger_class INT NOT NULL,
ENUM 1, 2, 3

2022-04-18 19:17 UTC, ChijiokeOrabueze commented on submissions/chijiokeOrabueze/database2/database2.sql
> +    passenger_class INT NOT NULL,
Done @ToluEnny24

2022-04-19 10:36 UTC, ToluEnny24 approved these changes

2022-04-19 10:36 UTC, merged