[DGPFET-166] Landing Page Validation
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1073
Opened 2022-04-22 15:11 UTC by Chukwuebukaj

![Web capture_22-4-2022_15551_127 0 0 1](https://user-images.githubusercontent.com/86056519/164742859-9a1b9f3b-d2a8-4014-b340-634d4de9cb21.jpeg)
![Web capture_22-4-2022_15544_127 0 0 1](https://user-images.githubusercontent.com/86056519/164742866-b6a9cb49-e75a-4f6e-9c3d-e4a8859c4a54.jpeg)

2022-04-25 03:15 UTC, ToluEnny24 requested changes
Hi @Chukwuebukaj well done on this task, however you are not to create new html and css files or even new images. The task is for you to make your already created and styled landing page verified... So remove all unnecessary files, add the Dom file link to your created landing page, also attach the screenshot of your output

2022-04-26 09:45 UTC, Chukwuebukaj commented
> Hi @Chukwuebukaj well done on this task, however you are not to create new html and css files or even new images. The task is for you to make your already created and styled landing page verified... So remove all unnecessary files, add the Dom file link to your created landing page, also attach the screenshot of your output

@ToluEnny24 Noted. I am on it. Thank you for the feedback.

2022-04-26 11:37 UTC, Chukwuebukaj commented
![Web capture_26-4-2022_123224_](https://user-images.githubusercontent.com/86056519/165291675-e1e69cfa-38de-432a-9b48-639dd82e2e56.jpeg)
![Web capture_26-4-2022_12331_](https://user-images.githubusercontent.com/86056519/165291706-ca875ee8-a6ea-4fa6-82a0-e2d1a25d7006.jpeg)
![Web capture_26-4-2022_123325_](https://user-images.githubusercontent.com/86056519/165291728-d1bbe5a1-00f0-4d24-a6eb-8688ba1d7d91.jpeg)

2022-04-26 12:08 UTC, ToluEnny24 approved these changes

2022-04-26 12:09 UTC, merged