[HIRFUS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1165
Opened 2022-05-05 09:41 UTC by Mirriam6

I have created my first task on the Databases

2022-05-05 11:58 UTC, ToluEnny24 requested changes
Effect the requested changes @Mirriam6

2022-05-05 11:58 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/foodbag.sql
> +	amount INT NOT NULL,
INT should be changed to decimal or float

2022-05-05 11:58 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/foodbag.sql
> +	type INT NOT NULL,
ENUM is better.

2022-05-05 11:58 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/foodbag.sql
> +	phone_number INT NOT NULL,
+234, +91 and all will have issues with INT, VARCHAR(50) is better

2022-05-05 11:58 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/foodbag.sql
> +	phone_number INT NOT NULL,
Take note as above.

2022-05-05 11:58 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/foodbag.sql
> +	payment_method VARCHAR (255) NOT NULL,
Its optional, NOT NULL is wrong

2022-05-05 13:00 UTC, Mirriam6 commented
I have modified my task, kindly review.

On Thu, May 5, 2022, 14:54 github-actions[bot] ***@***.***>
wrote:

> ***@***.***[bot]* requested changes on this pull request.
>
> There is no log file present in this pull request. Please ensure that you
> run the tests locally.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1165#pullrequestreview-963312817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXOUCVN2QEVQMHPHHA2BTR3VIPAG3ANCNFSM5VEP3LVA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-06 06:30 UTC, ToluEnny24 approved these changes

2022-05-06 06:30 UTC, merged