[HIRFUS-37] Database Design For A Transportation company
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1173
Opened 2022-05-06 09:00 UTC by Mirriam6

I have created a transportation database.

2022-05-06 09:51 UTC, ToluEnny24 requested changes
@Mirriam6 Please effect the requested changes.

2022-05-06 09:51 UTC, ToluEnny24 commented on submissions/mirriamSikalume/database/transportation_db.sql
> +    passengers_id INT NULL,
This table is not complete.
In the event of an accident during the trip, the company also needs to keep a record to show whether a passenger survived or not.

2022-05-06 14:18 UTC, ToluEnny24 approved these changes

2022-05-06 14:18 UTC, merged

2022-10-11 08:34 UTC, Mirriam6 commented
I have made changes to the transportation database.

On Fri, May 6, 2022, 15:08 github-actions[bot] ***@***.***>
wrote:

> ***@***.***[bot]* requested changes on this pull request.
>
> There is no log file present in this pull request. Please ensure that you
> run the tests locally.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1173#pullrequestreview-964628371>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXOUCVJSGPAERVSXJQHTYO3VIUKTVANCNFSM5VHQE4DA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>