[DGPFUS-3] Develop a Contact Form Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1402
Opened 2022-06-04 09:26 UTC by Datasphere-cloud

![contactPage](https://user-images.githubusercontent.com/89164184/171993345-77284900-10a7-4f78-84d0-a5fa99909d20.jpg)
- Design a contact page using HTML

2022-06-04 09:42 UTC, Datasphere-cloud commented
Let me make some changes

2022-06-06 08:19 UTC, ToluEnny24 requested changes
Well done @Datasphere-cloud I am concerned however, as to why you have your images stored in this folders. They should be stored in a different location and not in this folders. Please effect the changes.

2022-06-07 10:31 UTC, ToluEnny24 commented
Hi @Datasphere-cloud Well done on this task, However, I want you to add the images for your product page back into the images folder. Then use the correct url link for the images inside the <img src> tag. The ideal image link should be ../images/picture_name.jpg. Please effect this before your next push.

2022-06-07 10:31 UTC, ToluEnny24 approved these changes

2022-06-07 10:31 UTC, merged