[DGPFUS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1669
Opened 2022-07-08 19:42 UTC by ayodejimb

In this task, I designed a relational database for the FoodBag Store. Thank you.

2022-07-11 23:42 UTC, ToluEnny24 requested changes
@ayodejimb Well done please effect all requested changes.

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    name VARCHAR(100) NOT NULL,
let this accommodate more characters. 250 is fine

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    FOREIGN KEY (food_id) REFERENCES food_table(id)
the admin_id was not referenced as a foreign key

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    name VARCHAR(50) NOT NULL,
let the characters be 250.

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    email_address VARCHAR(50) NOT NULL,
This should accommodate more characters too

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    phone_number INT NOT NULL,
For a mobile number that starts with +2348078888, you will agree with me that, + wont be accepted as an integer or 08033003800, the 0 will be unaccepted too, likewise VARCHAR means capita letter O can be accepted as 0.

Just wanted you to understand the datatype you chose and what it entails

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    name VARCHAR(50) NOT NULL,
as usual

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    address VARCHAR(100) NOT NULL,
this should accommodate more characters

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    payment_method VARCHAR(20) NOT NULL,
This should be optional, we could have a first timer

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    card_number INT NOT NULL,
Not neccessary

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    card_name VARCHAR (50) NOT NULL,
Removr the card details there are other payment methods

2022-07-11 23:42 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/init.sql
> +    customer_id INT NOT NULL,
this should be null since it is optional

2022-07-15 13:46 UTC, ayodejimb commented
Thank you for those corrections. I have effected them all. Kindly check it out. Thanks.

2022-07-15 16:23 UTC, merged