[DGPFET-9] Printing Product Price with Javascript
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1715
Opened 2022-07-14 22:59 UTC by Usmaniyya

Check my PR

2022-07-15 16:54 UTC, ToluEnny24 requested changes
@Usmaniyya  Well done on your task, but you have a code factor error that needs to be fixed. Go to #git version control  and check the pinned messages.

2022-07-15 18:24 UTC, Usmaniyya commented
Ok ma'am 👌

On Fri, 15 Jul 2022, 17:54 FabunmiTolulopeEniola, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @Usmaniyya <https://github.com/Usmaniyya> Well done on your task, but you
> have a code factor error that needs to be fixed. Go to #git version control
> and check the pinned messages.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1715#pullrequestreview-1040563242>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALOUER5HLG7EDL5ADOFFY4TVUGJWBANCNFSM53TZLVNQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-07-15 20:20 UTC, Usmaniyya commented
Check now

2022-07-18 12:52 UTC, ToluEnny24 approved these changes

2022-07-18 12:52 UTC, merged