[DGPFUS-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1727
Opened 2022-07-16 11:36 UTC by ayodejimb

In this task, I designed a database for a transportation company based on the given criteria. Kindly check it out. Thanks.

2022-07-18 21:33 UTC, ToluEnny24 requested changes
Go through each of the comments and effect the changes. @ayodejimb

2022-07-18 21:33 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/transportCompany_database.sql
> +    sex VARCHAR(1) NOT NULL,
change this to accommodate more characters.

2022-07-18 21:33 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/transportCompany_database.sql
> +    FOREIGN KEY (class) REFERENCES passengers (id)
the class is a different detail different from the passengers id which is the link between this table and the passenger's table.

2022-07-18 21:33 UTC, ToluEnny24 commented on submissions/mubarakOlaoluwa/Database/transportCompany_database.sql
> +    FOREIGN KEY (id) REFERENCES trips (id)
id can not be foreign and Primary key. Rather you should have passengers-id which references the passengers table.

2022-07-19 10:00 UTC, ayodejimb commented
Thank you. I have made the corrections. Kindly review. Thanks!!

2022-07-20 09:22 UTC, merged