[DGPFET-10] The Software Developer conditionals
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1771
Opened 2022-07-24 11:38 UTC by chudylobor

2022-07-25 12:03 UTC, Mayowa2020 requested changes
@chudylobor, please effect the changes and revert. Thank!

2022-07-25 12:03 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> +		document.write(" " + "Software Developer ");
Please add a break tag here, to make your work look more presentable.

2022-07-25 12:03 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> +		document.write(" " + "Developer");
Please add a break tag here, to make your work look more presentable.

2022-07-25 12:03 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> +		document.write(" " + "Software");
Please add a break tag here, to make your work look more presentable.

2022-07-27 18:10 UTC, Mayowa2020 approved these changes
@chudylobor Well done. In the case of another time, kindly ensure a task is approved, before pushing in the next task. 

Approved...

2022-07-27 18:24 UTC, merged

2022-10-11 09:23 UTC, chudylobor commented
Thanks
I have made all corrections


On Mon, 25 Jul 2022 at 13:03, Bukola Oyetimehin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @chudylobor <https://github.com/chudylobor>, please effect the changes
> and revert. Thank!
> ------------------------------
>
> In submissions/godsonOgbuokiri/JavaScript/Conditionals/Index.html
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1771#discussion_r928792599>
> :
>
> > @@ -0,0 +1,13 @@
> +<!DOCTYPE html>
> +<html>
> +<head>
> +	<meta charset="utf-8">
> +	<meta name="viewport" content="width=device-width, initial-scale=1">
> +	<script src="conditionals.js"></script>
>
> @chudylobor <https://github.com/chudylobor>, It's good practice to have
> your Scripts placed in the of your HTML code. Please correct and revert.
> Thanks!
> ------------------------------
>
> In submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1771#discussion_r928802834>
> :
>
> > @@ -0,0 +1,18 @@
> +let p = 123-7;
> +for (let i = 1; i <= p; i++){
> +	if(i % 3 == 0 && i % 5 == 0) {
> +		document.write(" " + "Software Developer ");
>
> Please add a break tag here, to make your work look more presentable.
> ------------------------------
>
> In submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1771#discussion_r928803163>
> :
>
> > @@ -0,0 +1,18 @@
> +let p = 123-7;
> +for (let i = 1; i <= p; i++){
> +	if(i % 3 == 0 && i % 5 == 0) {
> +		document.write(" " + "Software Developer ");
> +	}
> +
> +	 else if(i % 5 == 0) {
> +		document.write(" " + "Developer");
>
> Please add a break tag here, to make your work look more presentable.
> ------------------------------
>
> In submissions/godsonOgbuokiri/JavaScript/Conditionals/conditionals.js
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1771#discussion_r928803843>
> :
>
> > @@ -0,0 +1,18 @@
> +let p = 123-7;
> +for (let i = 1; i <= p; i++){
> +	if(i % 3 == 0 && i % 5 == 0) {
> +		document.write(" " + "Software Developer ");
> +	}
> +
> +	 else if(i % 5 == 0) {
> +		document.write(" " + "Developer");
> +	}
> +
> +	else if(i % 3 == 0 ) {
> +		document.write(" " + "Software");
>
> Please add a break tag here, to make your work look more presentable.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1771#pullrequestreview-1049334260>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZKWKDVTU3EB6K3E67SKUBTVVZ7CFANCNFSM54PQ22TA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>