[DGPFET-166] Landing Page Validation
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1774
Opened 2022-07-24 21:58 UTC by temi-son

![image](https://user-images.githubusercontent.com/102083340/180667390-540b407e-be6b-4d56-bad9-c73ec05a731d.png)
![image](https://user-images.githubusercontent.com/102083340/180667446-ec28d730-8588-478d-84b7-26a05478bd22.png)

2022-07-25 11:14 UTC, ToluEnny24 requested changes
@temi-son this task requires that you validate the landing page you created previously not to create new files. So all I am expecting to see in the DOM folder is your landingpage.js file. Also You have codefactor error, do effect it. Visit the pinned messages in the #git and version control channel to help you resolve the issue.
 You also need to attach images of your output on the media

2022-07-26 13:45 UTC, ToluEnny24 commented
@temi-son are you fine? No response yet, are there any blockers?

2022-07-26 22:40 UTC, temi-son commented
Hi Tolu,

Thanks for checking up. I have just been abit busy.

I'll work on the corrections asap.

For the code factor error, I noticed it earlier but could not fix it.
The error is on the 'validate address function'  been declared but not
used.
Kindly advise on that.

Thank you
Johnson Temitope Abimbola
+234 (0) 817 936 6766



On Tue, Jul 26, 2022 at 2:46 PM FabunmiTolulopeEniola <
***@***.***> wrote:

> @temi-son <https://github.com/temi-son> are you fine? No response yet,
> are there any blockers?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/1774#issuecomment-1195506285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYK2WDEZKHMGXMB5O2WOROLVV7TZXANCNFSM54QJUSKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-28 09:19 UTC, ToluEnny24 approved these changes

2022-07-28 09:19 UTC, merged