[DCSFUS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1775
Opened 2022-07-25 02:29 UTC by Femmycode

2022-07-25 11:54 UTC, ToluEnny24 requested changes
@Femmycode Effect the requested changes

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +name VARCHAR(30) NOT NULL,
Change this to 250 to allow more characters.

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +amount FLOAT(4,2) NOT NULL,
FLOAT (10,2)

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +);
FOREIGN KEY is missing to Reference the admin_id for the admin table and food_id for the food table

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +name VARCHAR(30) NOT NULL,
Increase from 30 to 250 to accommodate more characters

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +email_address VARCHAR(40) NOT NULL,
This too should accommodate more characters

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +type  VARCHAR(16) NOT NULL,
This should be ENUM ("1", "2", "3", "4") that will be specific that we have 4 types

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +phone_number VARCHAR(18) NOT NULL,
This should not be VARCHAR, make it INT, so that if an applicant types in capital letter o and not Zero 0. it will be rejected.

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +payment_method VARCHAR(15) NOT NULL,
This is optional so NULL

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +name VARCHAR(30) NOT NULL,
As usual increase this character to accommodate more.

2022-07-25 11:54 UTC, ToluEnny24 commented on submissions/ayokofemi/Database 1/init.sql
> +PRIMARY KEY (id)
This table is incomlete without the FOREIGN key

2022-07-29 13:54 UTC, Mayowa2020 commented
@Femmycode, hope you are doing great. Any blockers? You are yet to effect the requested changes... Kindly effect and revert. Thanks! Well done and keep pushing.

2022-08-16 07:49 UTC, Mayowa2020 commented
A new PR was created by the Scholar, because he had to reclone the repo. The new PR has since been reviewed and merged.

2022-08-16 07:49 UTC, closed without merging