[SDFFEB-9] Printing Product Price With JavaScript
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1785
Opened 2022-07-25 23:53 UTC by adeyinka66

2022-07-26 18:05 UTC, ToluEnny24 requested changes
@adeyinka66 please effect the requested changes...

2022-07-26 18:05 UTC, ToluEnny24 commented on submissions/adeyinkaQuadri/javascript/index.html
> +    <script src="productlist.js"></script>
It is good coding practice that your src script should be located in the body tag not the head tag

2022-07-27 18:36 UTC, Mayowa2020 requested changes
@adeyinka66 Well done!  Please ensure a PR is merged before pushing another. You have to remove all the JS files and get the CSS task merged before adding the next task.

2022-07-28 09:33 UTC, ToluEnny24 approved these changes

2022-07-28 09:35 UTC, Mayowa2020 approved these changes

2022-07-28 09:36 UTC, merged