[HIRFUS-110] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1874
Opened 2022-08-11 13:37 UTC by AaronAsborn

My solution to the Algoritms and Data Structure

2022-08-11 20:51 UTC, Mayowa2020 requested changes
@AaronAsborn   Kindliy effect the changes and revert when done.
Please feel free to tag me @Mayowa2020 on GitHub,  or @Bukky on Slack.

2022-08-11 20:51 UTC, Mayowa2020 commented on submissions/aaronMubanga/algorithm/Algorithems.js
> +        for (let j = 0; j < ProductPrice.length; j++) {
Well done @AaronAsborn! The question states "Check the length of the product names in your products array". You are not expected to check for the length of the ProductPrice.

2022-08-12 16:34 UTC, AaronAsborn commented
![Screenshot 2022-08-12 at 13-24-20 Document](https://user-images.githubusercontent.com/93948423/184403578-23080ddc-a7b6-4492-82d7-3eb7088da322.png)

2022-08-12 16:41 UTC, Mayowa2020 approved these changes
Well done @AaronAsborn ! Approved...

2022-08-12 16:42 UTC, merged

2022-08-12 16:51 UTC, AaronAsborn commented
Thank you.!!