[DGPFET-110] Product Array Algorithm
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1881
Opened 2022-08-14 16:07 UTC by chudylobor

2022-08-16 07:41 UTC, Mayowa2020 approved these changes
In this case you have used the same const Price for 2 different values, which is not allowed. Please change it to let instead. Please read through: https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference .
Kindly effect the requested changes and tag me @Mayowa2020 on GitHub or @Bukky on Slack, once you are done.

2022-08-16 07:41 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/Product Array/arrays.js
> +    for (let n = 0; n < productPrice.length; n++) {
Well done @chudylobor ! Apparently your solution incorrect. What you should be looking is the length of the each product name not the length of the price.

2022-08-16 07:41 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/Product Array/arrays.js
> +            const price = productPrice[n] * 2;
How are constants used in JavaScript?
JavaScript Constants

Once a constant is initialized, we cannot change its value. Simply, a constant is a type of variable whose value cannot be changed. Note: If you are sure that the value of a variable won't change throughout the program, it's recommended to use const .

2022-08-16 07:41 UTC, Mayowa2020 commented on submissions/godsonOgbuokiri/Product Array/arrays.js
> +            const price = productPrice[n] / 2;
How are constants used in JavaScript?
JavaScript Constants

Once a constant is initialized, we cannot change its value. Simply, a constant is a type of variable whose value cannot be changed. Note: If you are sure that the value of a variable won't change throughout the program, it's recommended to use const .

2022-08-16 07:46 UTC, Mayowa2020 requested changes
Please effect the request changes for your PR to be merged.

2022-08-16 11:14 UTC, chudylobor commented
@Mayowa2020

2022-08-18 12:33 UTC, Mayowa2020 requested changes
Well done @chudylobor ! Please find attached and remove line 9 in the attached.
![Godson](https://user-images.githubusercontent.com/73591664/185395707-6bf2a253-99e3-4337-b52e-caff1377b9f8.jpg)

2022-08-19 11:04 UTC, Mayowa2020 approved these changes
Well done @chudylobor ! Approved...

2022-08-19 11:05 UTC, merged