[DCSFUS-2] Develop a Product Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1919
Opened 2022-08-22 00:46 UTC by Nimi-1

![Screenshot (7)](https://user-images.githubusercontent.com/104514656/185818888-a2a7c175-8ee8-486f-b644-bccd8cfa008a.png)
![Screenshot (8)](https://user-images.githubusercontent.com/104514656/185818914-3a7a6c8e-69c5-40d0-a2c9-08dc84bbe5d2.png)

2022-08-22 12:40 UTC, Mayowa2020 approved these changes
Well done @Nimi-1 ! Kindly run the test on your code and revert. Please tag me on Slack @Bukky      once you are done, or you are experiencing issues running the test.

2022-08-29 11:41 UTC, ToluEnny24 requested changes
Hi @Nimi-1 well done and your task has stayed longer than it should. Remove all hrefs tags pointing to product.html and replace with #. Also the success criteria states that you should us two images. Remove the other images and stick to two. You can use as many images for your 
 individual test work locally but not on this repo. If you need help you can reach out too

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +    <p> <a href="product.html"> Visit the HP store</a></p>
Here a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <p> <a href="product.html"> Add to Cart</a></p>
Here a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <a href="product.html"> 2022 Newest HP 15 15.6" HD Display</a>
Here the tag a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <a href="product.html"> 2021 Flagship Pavillon 15.6" HD Display</a>
Here the tag a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <p> <a href="product.html"> Home</a></p>
Here a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <a href="product.html"> HP 255 G8 Notebook, 15.6" HD Display</a>
Here a href should point to # not product.html

2022-08-29 11:41 UTC, ToluEnny24 commented on submissions/toluwanimiObafemi/html/product.html
> +            <a href="product.html"> 2022 Newest HP 15 15.6" HD Display</a>
REmove all href tags pointing to product .html and replace them with #

2022-08-29 18:40 UTC, merged