[DCSFUS-40] Querying The Transportation Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1922
Opened 2022-08-22 12:57 UTC by evansaizik

I was able to import and query the required data from the transportation database.
![Screenshot 2022-08-22 at 11 35 48](https://user-images.githubusercontent.com/108002096/185926625-782fd217-059c-4bb1-a9fb-60c6b376f04d.png)

2022-08-22 22:45 UTC, ToluEnny24 reviewed
Hi @evansaizik well done, but you need to reimport your data base

2022-08-22 22:45 UTC, ToluEnny24 commented on submissions/isaiahUsiholo/database/transportQuery.sql
> +-- the total number of people who survived = 290;
Your query is wrong, maybe you imported less than 891 people. Also select * from..... should be together with this new query

2022-08-22 22:45 UTC, ToluEnny24 commented on submissions/isaiahUsiholo/database/transportQuery.sql
> +-- the total number of people who did not survive = 424;
Same as above

2022-08-22 22:47 UTC, ToluEnny24 requested changes
Please effect the requested changes

2022-08-24 04:20 UTC, Mayowa2020 requested changes
Well done @evansaizik ! Your code is not running as it should. I tried running the test on your code and it kept failing. Try and reach out to me on Slack, let's work this out together.

2022-08-24 12:59 UTC, Mayowa2020 approved these changes
Well done @evansaizik ! Approved...

2022-08-24 13:14 UTC, merged