[DCSFUS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #1972
Opened 2022-08-27 20:36 UTC by joejoba

2022-08-29 16:46 UTC, ToluEnny24 requested changes
Please review all requested changes. @joejoba

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +    PRIMARY KEY (id)
this table shoud contain type too with the datatype as ENUM NOT NULL with the four type food categories

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +);
There should be FOREIGN KEYS referencing your admin_id and food_id

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +	name VARCHAR(100) NOT NULL,
name should allow more characters. make it 250

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +	type INT NOT NULL,
type should be ENUM 0 or 1

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +	payment_method VARCHAR(10),
This should be ENUM too.

2022-08-29 16:46 UTC, ToluEnny24 commented on submissions/josephOlasimbo/database/init.sql
> +);
FOREIGN KEYS are missing here too
customer_id should be optional

2022-09-05 21:58 UTC, Mayowa2020 approved these changes
Well done @joejoba! Approved...

2022-09-05 22:06 UTC, merged