[DGPFUS-27] Develop an E-commerce Store Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #2028
Opened 2022-09-06 14:50 UTC by Otruke

![SHOW TABLES 1_1](https://user-images.githubusercontent.com/107688538/188666559-4051fad9-081f-4ae9-b42b-26c59d370d29.PNG)
![show database1_1](https://user-images.githubusercontent.com/107688538/188666637-85126e3b-a2cb-4d1f-a350-686dc9caae9c.PNG)

2022-09-06 21:44 UTC, Otruke reviewed
![database 1_3](https://user-images.githubusercontent.com/107688538/188746345-1be3b8be-ba9a-4244-8c3a-16b55a62c39b.PNG)

2022-09-07 10:23 UTC, Mayowa2020 requested changes
Well done @Otruke! Kindiy make the requested changes and revert when done. Thank you!

2022-09-07 10:23 UTC, Mayowa2020 commented on submissions/rufusOtolorin/database/init.sql
> +    admin_id INT NOT NULL,
The admin_id should not be in this table.

2022-09-07 10:23 UTC, Mayowa2020 commented on submissions/rufusOtolorin/database/init.sql
> +    payment_method VARCHAR(255),
payment_method, etc as seen on the payment verification page. The first four columns mentioned are required and the other columns regarding payment are optional.
Change line 45 to:   payment_method ENUM('card', 'cash', 'transfer') NULL DEFAULT 'card'

2022-09-07 10:23 UTC, Mayowa2020 commented on submissions/rufusOtolorin/database/init.sql
> +    FOREIGN KEY (admin_id) REFERENCES admins (id)
This also is not needed in this table.

2022-09-07 10:23 UTC, Mayowa2020 commented on submissions/rufusOtolorin/database/init.sql
> +    admin_id INT NOT NULL,
Line 55 is not needed in this table.

2022-09-07 10:23 UTC, Mayowa2020 commented on submissions/rufusOtolorin/database/init.sql
> +    FOREIGN KEY (admin_id) REFERENCES admins (id)
Replace line 58 with FOREIGN KEY (customer_id) REFERENCES customer(id)

2022-09-08 16:45 UTC, Mayowa2020 approved these changes

2022-09-08 17:12 UTC, merged