[NDFFET-162] Create & Style the Landing Page for a Food Orderin
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #2243
Opened 2022-11-05 12:18 UTC by VivianEke

![Screenshot (66)](https://user-images.githubusercontent.com/112397159/200119460-ec627178-886a-49bf-a143-91e5bf20b688.png)
![Screenshot (67)](https://user-images.githubusercontent.com/112397159/200119468-050f06c0-00f2-4723-aafc-4af6c65d0412.png)

2022-11-07 11:03 UTC, ToluEnny24 requested changes
Hi @VivianEke remove the script src. ALso I would love to see your landing page. Make a quick 10 seconds video of the page and send to Tolulope on the slack channel.

2022-11-10 10:04 UTC, Mayowa2020 commented
Hello @VivianEke, Your CSS file is not present in this PR; please add the required CSS file.

2022-11-29 09:01 UTC, Mayowa2020 approved these changes
Well done @VivianEke! **Approved**

2022-12-07 12:06 UTC, ToluEnny24 approved these changes

2022-12-07 12:07 UTC, merged