[DGPFUS-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #2356
Opened 2022-12-07 04:25 UTC by chivicoko

- Created travel_sample database
- In the travel_sample database, I created passengers, passengers_details, and accident_cases tables

2022-12-07 04:51 UTC, chivicoko commented
@Mayowa2020 my PR is complaining about logfile. But logfile is there,
and I am sure I have done the test again and again to be certain. It's all checked

2022-12-07 09:07 UTC, Mayowa2020 requested changes
Well done @chivicoko! Kindly make all the requested changes and revert when done.

2022-12-07 09:07 UTC, Mayowa2020 commented on submissions/victorOkoye/database2/database2.sql
> +    status INT NOT NULL,
Change line 38 to:  status  BOOLEAN NOT NULL,

Boolean values are nothing but 0 and 1 i.e. either true or false. if the condition satisfies, it is true else it is false

2022-12-07 16:10 UTC, chivicoko commented
@Mayowa2020 I have made the corrections you pointed out I should make. The PR still failed.

2022-12-07 16:11 UTC, chivicoko commented
still log file issue

2022-12-07 20:17 UTC, Mayowa2020 approved these changes
Well done @chivicoko! **Approved**

2022-12-07 20:19 UTC, merged

2022-12-08 04:06 UTC, chivicoko commented
thanks