[CRBFUS-4] Add Page Navigation to your Pages
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #271
Opened 2021-11-10 08:16 UTC by IreneNakiyingi

2021-11-10 12:24 UTC, Ireti203 requested changes

2021-11-10 12:24 UTC, Ireti203 commented on submissions/ireneNakiyingi/HTML/bakery.html
> +            <a href="contact.html">Contact</a>
Are you sure this link works? @IreneNakiyingi

2021-11-10 12:24 UTC, Ireti203 commented on submissions/ireneNakiyingi/HTML/bakery.html
> +            <a href="contact.html">Contact</a>
Also, do all these pages exist? You ought to have only two pages for now. The contact page and the product page

2021-12-20 21:16 UTC, ToluEnny24 commented
@IreneNakiyingi what blockers have caused this delay in your pr?

2021-12-21 03:10 UTC, IreneNakiyingi commented
> @IreneNakiyingi what blockers have caused this delay in your pr?

Hello,  I made three pull requests in this module.  One had an error in the naming (wrong names to the wrong files) and I was told to make another. But it was never merged. Logfile Json failed to be added by me.

2022-01-06 09:23 UTC, ToluEnny24 approved these changes
Manually reviewed..

2022-01-06 09:23 UTC, merged