[DCSFUS-2] Developed a product Page using HTML
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #291
Opened 2021-11-25 23:49 UTC by Saypauloh

This is my second pull request
In this PR, i have added my second task of creating an ecommerce homepage.

2021-11-26 10:55 UTC, Ireti203 requested changes
The homepage.html file should be in the HTML folder. Remove the dufuna folder and rename the homepage folder to HTML.

2021-11-26 10:57 UTC, Ireti203 requested changes
Also, your images should be in an images folder. You don't have to create several folders.

2021-11-27 14:44 UTC, Ireti203 requested changes

2021-11-27 14:44 UTC, Ireti203 commented on submissions/paulOlubunmi/HTML/index.html
> +           <!-- <image src="image/pa3.jpg "></image>-->
Remove commented out code.

2021-11-27 14:51 UTC, Ireti203 requested changes
Your product page ought to have only 2 images, but I can see that you have more than 2. Kindly update that.

Always ensure you follow the instructions on the task.

2021-11-27 15:34 UTC, Saypauloh commented
Done ma

On Sat, 27 Nov 2021, 15:51 Ireti203, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Your product page ought to have only 2 images, but I can see that you have
> more than 2. Kindly update that.
>
> Always ensure you follow the instructions on the task.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/291#pullrequestreview-817138231>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWRRZMRYC55ZBKHK3ZOABDDUODV6RANCNFSM5IZPVWPQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-27 15:36 UTC, Ireti203 approved these changes

2021-11-27 15:37 UTC, merged