add tests for product price printing javascript task
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #55
Opened 2021-06-29 07:32 UTC by Morenayd

2021-06-29 10:49 UTC, ToluAkin requested changes

2021-06-29 10:49 UTC, ToluAkin commented on tests/conditionals_js/conditionals_test.js
> +var webdriver = require('selenium-webdriver');
Instead of `var` use `const` @Morenayd

2021-06-29 10:49 UTC, ToluAkin commented on tests/product_price_printing/test.js
> +        // driver.quit()
I think this should be uncommented

2021-06-29 10:49 UTC, ToluAkin commented on tests/product_price_printing/test.js
> +        var productList = [{ productName: "a", imageUrl: "b", productPrice: "4" }, { productName: "a", imageUrl: "b", productPrice: "4" }, { productName: "a", imageUrl: "b", productPrice: "4" }]
You are not using `await` in your task. You should remove `async`

2021-06-29 10:49 UTC, ToluAkin commented on tests/product_price_printing/test.js
> +        var productList = [{ productName: "a", imageUrl: "b", productPrice: "4" }, { productName: "a", imageUrl: "b", productPrice: "4" }, { productName: "a", imageUrl: "b", productPrice: "4" }]
You are not using `await` in your task. You should remove `async`

2021-06-29 10:49 UTC, ToluAkin commented on tests/product_price_printing/test.js
> +const { Builder, By } = require("selenium-webdriver");
You are not using `assert`, `chromedriver` and `By` in this test. You should remove it.

2021-06-29 11:14 UTC, Ireti203 commented
Weldone @Morenayd 

So, I think you should try to set up the repo on your computer so you can also run the test at your end. You ought to have a bash script in the folder to run the test. You can check previous tests in this repo to see the structure and how it works.

2021-07-01 10:07 UTC, ToluAkin requested changes
Can you add a screenshot of the result of the test to your PR? Thanks.

2021-07-01 10:07 UTC, ToluAkin commented on tests/conditionals_js/conditionals_test.js
> +    it('test case: Prints out the value of array', async () => {
This block of code is not well formatted @Morenayd

2021-07-01 10:49 UTC, Ireti203 requested changes

2021-07-01 10:49 UTC, Ireti203 commented on tests/conditionals_js/test.sh
> +env FILE_PATH=$submission_directory/$folder_name/$html_file mocha $PWD/landing_page.js --reporter mochawesome --reporter-options reportDir=$customReportDir,reportFilename=$customReportFilename,quiet=
Kindly update this like of code appropriately. The script you want to run is conditionals_test.js and not landing_page.js

2021-07-01 10:49 UTC, Ireti203 commented on tests/product_price_printing/test.sh
> +env FILE_PATH=$submission_directory/$folder_name/$html_file mocha $PWD/landing_page.js --reporter mochawesome --reporter-options reportDir=$customReportDir,reportFilename=$customReportFilename,quiet=
Same here @Morenayd

2021-07-15 11:20 UTC, merged