[HIRFUS-167] Vendors Page Validation
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #747
Opened 2022-03-10 08:43 UTC by VincentNjele

-In this PR
-I have put validation on the vendors page
![VendorsDOMJS](https://user-images.githubusercontent.com/99276899/157622256-6ad9c0e3-1e51-40a5-b522-55ce8ab760bd.png)
![VondorsDOMJS@](https://user-images.githubusercontent.com/99276899/157622291-8a3c4fcb-022b-41e7-a161-94958a0dafd3.png)

2022-03-10 09:00 UTC, ToluEnny24 requested changes
Please remove your styles from your dom files

2022-03-10 09:00 UTC, ToluEnny24 commented on submissions/vincentNjele/Dom/vendors.js
> +            addToCart.style.width = "150px";
It is not good coding practice that your styles should be inside your html or js files

2022-03-11 11:12 UTC, ToluEnny24 approved these changes
Well done....

2022-03-11 11:13 UTC, merged

2022-03-11 11:25 UTC, VincentNjele commented
Thank you so much.

On Fri, Mar 11, 2022, 13:13 FabunmiTolulopeEniola ***@***.***>
wrote:

> Merged #747
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/747> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/747#event-6224142024>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXVNQY4RVLDKC2U7XFTWWETU7MTFVANCNFSM5QL5QI3Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> .com>
>