[DGPFUS-37] Database Design For A Transportation Company
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #779
Opened 2022-03-14 15:51 UTC by bukiz-cloud

A created a DATABASE for a Transportation company

2022-03-14 16:26 UTC, ToluEnny24 requested changes
Please look through and effect changes immediately

2022-03-14 16:26 UTC, ToluEnny24 commented on submissions/bukunmiAdeniyi/database1/init.sql
> +    passenger_status ENUM('Survived', 'Not Survived', 'comtemplating'),
contemplating kwa? Boolean is fine, yes or no is fine

2022-03-14 16:26 UTC, ToluEnny24 commented on submissions/bukunmiAdeniyi/database1/init.sql
> +     passenger_class VARCHAR(100) NOT NULL,
passenger_class should be ENUM class 1, 2 or 3

2022-03-14 21:07 UTC, bukiz-cloud reviewed
The necessary changes have been done

2022-03-15 10:34 UTC, ToluEnny24 approved these changes

2022-03-15 10:34 UTC, merged