[HIRFUS-40] Querying the Transportation Database
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #800
Opened 2022-03-17 07:07 UTC by VincentNjele

- In this PR
- I have created an accident_detail.sql file 
- And I have added the related queries and results

2022-03-17 08:48 UTC, ToluEnny24 requested changes
Please effect requested changes.

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +SELECT  count(s.survival_status) FROM survival_table s WHERE s.survival_status = 1
This query is giving a wrong answer. Hint:count should be COUNT (*) as accident_survivals where blah blah blah.

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +/*Number of survivors = 290   */
This answer is incorrect

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +SELECT  COUNT(s.survival_status) FROM survival_table s WHERE s.survival_status = 0
Same as question 1 above

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +/*3. Those who were <27 and embarked at Queenstown, I could not get those that embarked and Q and C in the same query because they are all in the same column  */
Its in the same column. yes but it is possible to get those that embarked from Q and C

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +AND t.embarkatiON_point = 'Q'
hint for Q and C is embarkation_point = ('Q'|'S');

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +AND t.num_of_siblings_or_spouces > 0
Good

2022-03-17 08:48 UTC, ToluEnny24 commented on submissions/vincentNjele/Database/accident_detail.sql
> +
They are 9 in number.

2022-03-18 09:05 UTC, ToluEnny24 approved these changes

2022-03-18 09:07 UTC, ToluEnny24 approved these changes
Well done @VincentNjele

2022-03-18 09:07 UTC, merged

2022-03-18 09:57 UTC, VincentNjele commented
Thank you


On Fri, Mar 18, 2022 at 11:08 AM FabunmiTolulopeEniola <
***@***.***> wrote:

> Merged #800
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/800> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Dufuna-CodeCamp/Dufuna-CodeCamp-21/pull/800#event-6264799559>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXVNQY3GYMYDJLYCNVFDX33VARBXNANCNFSM5Q6BUDUQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>