[DGPFUS-162] Create & Style the Landing Page for a Food Orderin
Dufuna-CodeCamp/Dufuna-CodeCamp-21 pull request #801
Opened 2022-03-17 08:18 UTC by mary699

![screencapture-127-0-0-1-5500-html-order-html-2022-03-17-09_17_18](https://user-images.githubusercontent.com/69188881/158766341-70c36373-6ba1-4284-ac6d-2a6f06dac400.png)
![screencapture-127-0-0-1-5500-html-order-html-2022-03-17-09_06_41](https://user-images.githubusercontent.com/69188881/158766359-a3cd7b16-0568-4c1c-8835-7a52ac8e0115.png)

2022-03-17 09:13 UTC, ToluEnny24 requested changes

2022-03-18 09:12 UTC, ToluEnny24 commented
@mary699 Well done. You have about 19 codefactor errors to fix. They are majorly unexpected unit i.e 0 is 0 not 0px.
Click on the details, it will give you hints to the line where the error is and how to resolve it

2022-03-20 10:18 UTC, mary699 commented
> @mary699 Well done. You have about 19 codefactor errors to fix. They are majorly unexpected unit i.e 0 is 0 not 0px. Click on the details, it will give you hints to the line where the error is and how to resolve it



@ToluEnny24  Done

2022-03-21 10:45 UTC, ToluEnny24 approved these changes

2022-03-21 10:45 UTC, merged